// <auto-generated />
using System;
using LocalHistoryWebsite.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LocalHistoryWebsite.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LocalHistoryWebsite.Models.HistoryImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HistoryPostId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HistoryPostId");

                    b.ToTable("HistoryImages");
                });

            modelBuilder.Entity("LocalHistoryWebsite.Models.HistoryPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("HistoryPosts");
                });

            modelBuilder.Entity("LocalHistoryWebsite.Models.PostReaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HistoryPostId")
                        .HasColumnType("int");

                    b.Property<int>("ReactionType")
                        .HasColumnType("int");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HistoryPostId");

                    b.ToTable("PostReactions");
                });

            modelBuilder.Entity("LocalHistoryWebsite.Models.HistoryImage", b =>
                {
                    b.HasOne("LocalHistoryWebsite.Models.HistoryPost", "HistoryPost")
                        .WithMany("Images")
                        .HasForeignKey("HistoryPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HistoryPost");
                });

            modelBuilder.Entity("LocalHistoryWebsite.Models.PostReaction", b =>
                {
                    b.HasOne("LocalHistoryWebsite.Models.HistoryPost", "HistoryPost")
                        .WithMany("Reactions")
                        .HasForeignKey("HistoryPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HistoryPost");
                });

            modelBuilder.Entity("LocalHistoryWebsite.Models.HistoryPost", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Reactions");
                });
#pragma warning restore 612, 618
        }
    }
}
